#!/bin/sh
MYSQL_VERSION=5.7.17
docker run -it --link hermitage-mysql:mysql --rm mysql:$MYSQL_VERSION sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'